[pytest]
addopts =
    --base-url https://www.saucedemo.com
    --html=report.html --self-contained-html
    --screenshot only-on-failure
    --tracing retain-on-failure
markers =
    smoke: quick checks for every push
